name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '16.0.2' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build -x test
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime -x test
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage -x test
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: fusion-of-souls-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/package/install/*.dmg
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: fusion-of-souls-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/package/install/*.msi
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: fusion-of-souls-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/package/install/*.deb
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: fusion-of-souls-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/package/install/*.rpm
