name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
    - name: Setup Wrapper
      run: ./gradlew --info --stacktrace wrapper
    - name: Execute tests
      run: ./gradlew --info --stacktrace test
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Upload Installation Artifact(s)
      uses: actions/upload-artifact@v2
      with:
        name: fusion-of-souls-${{ matrix.os }}-installer
        path: build/package/install/*
